services:
  backend:
    build: .
    container_name: pca_plot_assistant
    volumes:
      - .:/app
      - /app/node_modules # Protects modules installed inside the container
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      # Use env variables to connect to external DB (host).
      - DATABASE_URL=postgresql://${PSQL_USER}:${PSQL_PASSWORD}@${PSQL_HOSTNAME}:${PSQL_LOCAL_PORT}/${PSQL_DBNAME}?schema=public
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: ./pca-plot-frontend
    container_name: pca_plot_frontend
    working_dir: /app
    volumes:
      - ./pca-plot-frontend:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true
